version: 2.1

executors:
  my-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_directory: /app

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Install .NET Core Tools
          command: dotnet tool restore
      - run:
          name: Build
          command: dotnet build --configuration Release --verbosity minimal
      - run:
          name: Unit Tests
          command: dotnet test --configuration Release --verbosity minimal --logger trx
      - run:
          name: Transform Unit Test Results
          command: dotnet trx2junit tests/ArgentPonyWarcraftClient.Tests/TestResults/*.trx --output out/test-results
          when: always
      - store_test_results:
          path: out/test-results
      - run:
          name: Pack NuGet Package
          command: |
              chmod +x build/semver
              . build/set-version.sh
              dotnet pack --configuration Release --output ./out/nupkgs -p:Version="${PACKAGE_VERSION}" --include-symbols --include-source --verbosity minimal
      - store_artifacts:
          path: out/nupkgs
          destination: nupkgs
      - persist_to_workspace:
          root: /app
          paths:
            - out/nupkgs/*.nupkg

  deploy:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /app
      - run:
          name: NuGet Push
          command: dotnet nuget push /app/out/nupkgs/*.nupkg --api-key ${NUGET_KEY} --source https://api.nuget.org/v3/index.json

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              # Build for all commits to any branch. When a commit is tagged, only build if it's an appropriately-formatted SemVer 2.0 tag.
              only: /^v\d+\.\d+\.\d+(?:-alpha(?:\.\d+)?)?$/
      - deploy:
          requires:
            - build
          filters:
            # Only deploy when tagged with an appropriately-formatted SemVer 2.0 tag.
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(?:-alpha(?:\.\d+)?)?$/
